const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const inputPath = path.join(__dirname, "app.ts");
const outputPath = path.join(__dirname, "generated", "ui_app_data.h");

function loadAppConfig(source) {
  const marker = "export default";
  const start = source.indexOf(marker);

  if (start < 0) {
    throw new Error("frontend/app.ts must contain `export default`.");
  }

  let expression = source.slice(start + marker.length).trim();
  expression = expression.replace(/\s+satisfies\s+UiApp\s*;?\s*$/, "");

  return vm.runInNewContext(`(${expression})`, {}, { filename: inputPath });
}

function assertString(value, field) {
  if (typeof value !== "string" || value.length === 0) {
    throw new Error(`${field} must be a non-empty string.`);
  }
}

function assertInt(value, field) {
  if (!Number.isInteger(value)) {
    throw new Error(`${field} must be an integer.`);
  }
}

function classNames(value) {
  if (value === undefined) {
    return [];
  }

  assertString(value, "className");
  return value.split(/\s+/).filter(Boolean);
}

function parseColor(value, field) {
  assertString(value, field);

  if (!/^#[0-9a-fA-F]{6}$/.test(value)) {
    throw new Error(`${field} must use #RRGGBB.`);
  }

  return `0x00${value.slice(1).toLowerCase()}`;
}

function cString(value) {
  assertString(value, "string");
  return JSON.stringify(value);
}

function cRawString(value) {
  if (typeof value !== "string") {
    throw new Error("string must be a string.");
  }

  return JSON.stringify(value);
}

function optionalString(value) {
  if (value === undefined) {
    return "";
  }

  assertString(value, "string");
  return value;
}

function optionalColor(value, fallback, field) {
  if (value === undefined) {
    return fallback;
  }

  parseColor(value, field);
  return value;
}

function optionalInt(value, fallback, field) {
  if (value === undefined) {
    return fallback;
  }

  assertInt(value, field);
  return value;
}

function validateApp(app) {
  assertString(app.initialScreen, "initialScreen");

  if (!Array.isArray(app.screens) || app.screens.length === 0) {
    throw new Error("screens must be a non-empty array.");
  }

  const screenIds = new Set();

  app.screens.forEach((screen, screenIndex) => {
    assertString(screen.id, `screens[${screenIndex}].id`);
    parseColor(screen.background, `screens[${screenIndex}].background`);

    if (screenIds.has(screen.id)) {
      throw new Error(`duplicate screen id: ${screen.id}`);
    }

    screenIds.add(screen.id);

    if (!Array.isArray(screen.labels)) {
      throw new Error(`screens[${screenIndex}].labels must be an array.`);
    }

    if (!Array.isArray(screen.buttons)) {
      throw new Error(`screens[${screenIndex}].buttons must be an array.`);
    }

    screen.labels.forEach((label, labelIndex) => {
      assertString(label.text, `screens[${screenIndex}].labels[${labelIndex}].text`);
      assertInt(label.x, `screens[${screenIndex}].labels[${labelIndex}].x`);
      assertInt(label.y, `screens[${screenIndex}].labels[${labelIndex}].y`);
      parseColor(label.color, `screens[${screenIndex}].labels[${labelIndex}].color`);
    });

    screen.buttons.forEach((button, buttonIndex) => {
      const prefix = `screens[${screenIndex}].buttons[${buttonIndex}]`;
      classNames(button.className);
      assertString(button.id, `${prefix}.id`);
      assertString(button.text, `${prefix}.text`);
      optionalString(button.subtitle);
      assertInt(button.x, `${prefix}.x`);
      assertInt(button.y, `${prefix}.y`);
      assertInt(button.w, `${prefix}.w`);
      assertInt(button.h, `${prefix}.h`);
      parseColor(button.bg, `${prefix}.bg`);
      parseColor(button.fg, `${prefix}.fg`);
      optionalColor(button.accent, button.fg, `${prefix}.accent`);
      optionalInt(button.radius, 26, `${prefix}.radius`);
      assertString(button.target, `${prefix}.target`);
    });
  });

  if (!screenIds.has(app.initialScreen)) {
    throw new Error(`initialScreen does not exist: ${app.initialScreen}`);
  }

  app.screens.forEach((screen) => {
    screen.buttons.forEach((button) => {
      if (button.target === "album") {
        return;
      }

      if (!screenIds.has(button.target)) {
        throw new Error(`button ${button.id} targets missing screen: ${button.target}`);
      }
    });
  });
}

function emitHeader(app) {
  const lines = [];

  lines.push("/* Generated by frontend/build-ui.js. Do not edit by hand. */");
  lines.push("#ifndef UI_APP_DATA_H");
  lines.push("#define UI_APP_DATA_H");
  lines.push("");
  lines.push("typedef struct {");
  lines.push("    const char *text;");
  lines.push("    int x;");
  lines.push("    int y;");
  lines.push("    unsigned int color;");
  lines.push("} ui_label_def_t;");
  lines.push("");
  lines.push("typedef struct {");
  lines.push("    const char *id;");
  lines.push("    const char *text;");
  lines.push("    const char *subtitle;");
  lines.push("    int x;");
  lines.push("    int y;");
  lines.push("    int w;");
  lines.push("    int h;");
  lines.push("    unsigned int bg;");
  lines.push("    unsigned int fg;");
  lines.push("    unsigned int accent;");
  lines.push("    int radius;");
  lines.push("    const char *target;");
  lines.push("} ui_button_def_t;");
  lines.push("");
  lines.push("typedef struct {");
  lines.push("    const char *id;");
  lines.push("    unsigned int background;");
  lines.push("    const ui_label_def_t *labels;");
  lines.push("    int label_count;");
  lines.push("    const ui_button_def_t *buttons;");
  lines.push("    int button_count;");
  lines.push("} ui_screen_def_t;");
  lines.push("");

  app.screens.forEach((screen, screenIndex) => {
    lines.push(`static const ui_label_def_t ui_screen_${screenIndex}_labels[] = {`);
    screen.labels.forEach((label) => {
      lines.push(`    {${cString(label.text)}, ${label.x}, ${label.y}, ${parseColor(label.color, "label.color")}},`);
    });
    lines.push("};");
    lines.push("");

    lines.push(`static const ui_button_def_t ui_screen_${screenIndex}_buttons[] = {`);
    screen.buttons.forEach((button) => {
      const subtitle = optionalString(button.subtitle);
      const accent = optionalColor(button.accent, button.fg, "button.accent");
      const radius = optionalInt(button.radius, 26, "button.radius");

      lines.push(
        `    {${cString(button.id)}, ${cString(button.text)}, ${cRawString(subtitle)}, ` +
          `${button.x}, ${button.y}, ` +
          `${button.w}, ${button.h}, ${parseColor(button.bg, "button.bg")}, ` +
          `${parseColor(button.fg, "button.fg")}, ${parseColor(accent, "button.accent")}, ` +
          `${radius}, ` +
          `${cString(button.target)}},`,
      );
    });
    lines.push("};");
    lines.push("");
  });

  lines.push("static const ui_screen_def_t ui_app_screens[] = {");
  app.screens.forEach((screen, screenIndex) => {
    lines.push(
      `    {${cString(screen.id)}, ${parseColor(screen.background, "screen.background")}, ` +
        `ui_screen_${screenIndex}_labels, ` +
        `(int)(sizeof(ui_screen_${screenIndex}_labels) / sizeof(ui_screen_${screenIndex}_labels[0])), ` +
        `ui_screen_${screenIndex}_buttons, ` +
        `(int)(sizeof(ui_screen_${screenIndex}_buttons) / sizeof(ui_screen_${screenIndex}_buttons[0]))},`,
    );
  });
  lines.push("};");
  lines.push("");
  lines.push(`static const int ui_app_screen_count = (int)(sizeof(ui_app_screens) / sizeof(ui_app_screens[0]));`);
  lines.push(`static const char *ui_app_initial_screen = ${cString(app.initialScreen)};`);
  lines.push("");
  lines.push("#endif");
  lines.push("");

  return lines.join("\n");
}

const source = fs.readFileSync(inputPath, "utf8");
const app = loadAppConfig(source);

validateApp(app);
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, emitHeader(app));

console.log(path.relative(root, outputPath));
